import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dee0ff",
        "on-secondary": "#ffffff",
        "on-primary-container": "#b9c1ff",
        tertiary: "#4e3600",
        "inverse-surface": "#2f3036",
        surface: "#faf8ff",
        "surface-container-high": "#e8e7ef",
        "surface-tint": "#2e4ae7",
        "inverse-on-surface": "#f1f0f8",
        "on-tertiary-container": "#f5bb46",
        primary: "#0023af",
        "on-secondary-fixed-variant": "#5228ab",
        "tertiary-container": "#6b4c00",
        "primary-container": "#1a3adb",
        "on-surface-variant": "#444655",
        outline: "#757687",
        "on-background": "#1a1b21",
        "inverse-primary": "#bbc3ff",
        "on-tertiary-fixed-variant": "#5d4200",
        "on-primary-fixed-variant": "#002bcf",
        error: "#ba1a1a",
        "on-secondary-fixed": "#22005d",
        "on-tertiary-fixed": "#271900",
        "surface-container-lowest": "#ffffff",
        background: "#faf8ff",
        "on-surface": "#1a1b21",
        "tertiary-fixed-dim": "#f7bd48",
        "on-primary-fixed": "#000e5e",
        "tertiary-fixed": "#ffdea6",
        "surface-container-low": "#f4f3fb",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#cfbcff",
        "on-error": "#ffffff",
        "surface-dim": "#dad9e1",
        "on-secondary-container": "#350087",
        "surface-variant": "#e2e2e9",
        "outline-variant": "#c5c5d8",
        "surface-bright": "#faf8ff",
        "on-error-container": "#93000a",
        secondary: "#6a45c4",
        "surface-container": "#eeedf5",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#a07dfe",
        "secondary-fixed": "#e9ddff",
        "surface-container-highest": "#e2e2e9",
        "primary-fixed-dim": "#bbc3ff",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        playfair: ["Playfair Display", "serif"],
      },
      spacing: {
        gutter: "32px",
        "section-md": "80px",
        "section-lg": "120px",
        "container-max": "1200px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      animation: {
        "fade-up": "fadeUp 0.7s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-in": "fadeIn 0.6s ease forwards",
        "slide-left": "slideLeft 0.7s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "pulse-slow": "pulse 3s infinite",
        float: "float 6s ease-in-out infinite",
        "spin-slow": "spin 20s linear infinite",
      },
      keyframes: {
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideLeft: {
          "0%": { opacity: "0", transform: "translateX(-30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
      boxShadow: {
        card: "0 4px 24px rgba(26, 58, 219, 0.08)",
        "card-hover": "0 8px 32px rgba(26, 58, 219, 0.16)",
        glow: "0 0 40px rgba(26, 58, 219, 0.2)",
      },
    },
  },
  plugins: [],
};

export default config;
